Code improvements

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,6 +8,7 @@ if [ "$#" -gt 1 ]; then
   echo "Too many arguments" >&2
   exit 1
 fi
+
 if [ "$#" -eq 1 ] && ! [ "$1" = "--symlink" ] && ! [ "$1" = "-s" ]; then
   echo "Invalid parameter: $1" >&2
   exit 1
@@ -15,6 +16,7 @@ fi
 
 # Some important variables
 SCRIPT_DIR=$(realpath $(dirname $0))
+
 CONFIGS=$SCRIPT_DIR/configs # Where all the config files reside
 LISTS_DIR=$SCRIPT_DIR/lists # Where all the list reside
 AUR=$LISTS_DIR/aur          # AUR pkgs list
@@ -23,16 +25,12 @@ PACMAN=$LISTS_DIR/pacman    # Pacman pkgs list
 UCONFIG=$LISTS_DIR/uconfig  # User records
 SCONFIG=$LISTS_DIR/sconfig  # System-wide records
 
-# Check required files
-check_files_presence() {
-  for file in "$@"; do
-    if [ ! -e $file ]; then
-      echo "Missing required file: $file" >&2
-      exit 1
-    fi
-  done
-}
-check_files_presence $AUR $PACMAN $PYTHON $UCONFIG $SCONFIG $CONFIGS
+for file in $AUR $PACMAN $PYTHON $UCONFIG $SCONFIG $CONFIGS; do
+  if [ ! -e $file ]; then
+    echo "Missing required file: $file" >&2
+    exit 1
+  fi
+done
 
 # Install pkgs using pacman and if it fails exit with code 1
 sudo pacman -S --needed --noconfirm --overwrite "*" - <$PACMAN
